# Generated by Django 5.2.1 on 2025-05-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('data_of_updation', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('A', 'To Do'), ('B', 'In Progress'), ('C', 'Done')], default='A', max_length=1)),
            ],
        ),
    ]
